[WIP] Julius関連のhspプログラムが動作しない問題の解決
OmeSatoFoundation/ome2023 pull request #56
Opened 2023-06-15 16:15 UTC by tikisi

## 主な変更
- `ome2019/bin/julius_conf/`から必要なものだけを`/usr/loca/bin`に配置
  ```
  julius_conf/
  ├── default.jconf
  └── model
      ├── lang_m
      │   └── bccwj.60k.htkdic
      └── phone_m
          ├── jnas-tri-3k16-gid.binhmm
          └── logicalTri
  ```
- `ome2019/bin/stopjulius.sh`を`/usr/loca/bin`に配置
- `.dic`の指定方法を絶対パスから相対パスへ変更(`init_julius "kudamono.dic"`に変更)

2023-06-15 16:15 UTC, tikisi commented
このブランチでビルドしたイメージでの動作チェックはこれから

2023-06-16 02:58 UTC, RollMan commented on contrib/JuliusMisc/Makefile.am
> +bindata_DATA = \
できれば default.jconf とその他も `/usr/local/share/dic` に置きたい……

そして julius.sh では /usr/local/share/dic を読む

2023-06-16 03:00 UTC, RollMan approved these changes

2023-06-16 05:53 UTC, RollMan requested changes

2023-06-16 05:53 UTC, RollMan commented on contrib/JuliusMisc/Makefile.am
> +bindata_DATA = \
nodist を付けてディレクトリ構造を保持する必要がある．

2023-06-16 07:40 UTC, merged